begin;
create policy bootstrap_editor_insert on public.trips for insert to authenticated with check (public.commerce_editor() and created_by = auth.uid());
create policy bootstrap_editor_update on public.trips for update to authenticated using (public.commerce_editor()) with check (public.commerce_editor());
create policy bootstrap_editor_delete on public.trips for delete to authenticated using (public.commerce_editor());
create policy bootstrap_editor_insert on public.trip_expenses for insert to authenticated with check (public.commerce_editor() and created_by = auth.uid());
create policy bootstrap_editor_update on public.trip_expenses for update to authenticated using (public.commerce_editor()) with check (public.commerce_editor());
create policy bootstrap_editor_delete on public.trip_expenses for delete to authenticated using (public.commerce_editor());
create policy bootstrap_editor_insert on public.products for insert to authenticated with check (public.commerce_editor() and created_by = auth.uid());
create policy bootstrap_editor_update on public.products for update to authenticated using (public.commerce_editor()) with check (public.commerce_editor());
create policy bootstrap_editor_delete on public.products for delete to authenticated using (public.commerce_editor());
create policy bootstrap_editor_insert on public.product_variants for insert to authenticated with check (public.commerce_editor() and created_by = auth.uid());
create policy bootstrap_editor_update on public.product_variants for update to authenticated using (public.commerce_editor()) with check (public.commerce_editor());
create policy bootstrap_editor_delete on public.product_variants for delete to authenticated using (public.commerce_editor());
create policy bootstrap_editor_insert on public.product_categories for insert to authenticated with check (public.commerce_editor() and created_by = auth.uid());
create policy bootstrap_editor_update on public.product_categories for update to authenticated using (public.commerce_editor()) with check (public.commerce_editor());
create policy bootstrap_editor_delete on public.product_categories for delete to authenticated using (public.commerce_editor());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-images','product-images',true,10485760,array['image/jpeg','image/png','image/webp','image/avif']);
create policy bootstrap_product_images_read on storage.objects for select to anon,authenticated using(bucket_id='product-images');
create policy bootstrap_product_images_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.commerce_editor());
create policy bootstrap_product_images_update on storage.objects for update to authenticated using(bucket_id='product-images' and public.commerce_editor()) with check(bucket_id='product-images' and public.commerce_editor());
create policy bootstrap_product_images_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and public.commerce_editor());
create index bootstrap_products_trip on public.products(trip_code);
create index bootstrap_variants_product on public.product_variants(product_id);
create index bootstrap_expenses_trip on public.trip_expenses(trip_code);
commit;
